<a href="https://colab.research.google.com/github/marioarsw/AnaliticaDescriptiva/blob/main/practicas/practica12_13_14_16_267370.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Maestría en Inteligencia Artificial y Analítica de Datos


*   Curso: Programación para Analítica Descriptiva y Predictiva
*   Semestre: Enero-Junio
*   Profesor: Dr. Vicente García Jiménez

## Mario Amador - 267370.

El objetivo de esta actividad es que los estudiantes practiquen los temas vistos de carga de datos, normalización de nombres de columnas, separación y unión de columnas, errores en los tipos de datos. Todo es en un conjunto de datos utilizando Pandas en Python.

Instrucciones:

1. Descarga el archivo CSV, miaad-nyc-r-s.csv, proporcionado en esta tarea. También lo puedes encontrar en recursos.
2. Crea un notebook en colab y guarda el archivo csv descargado en tu drive.
3. Agrega secciones en el colab poniendo como título el nombre de la práctica

# Práctica 12: Carga de Datos

Al final del archivo contiene una línea que dice "Esta es una línea que no deberías cargar". Esta línea es irrelevante por lo tanto al cargar el CSV a un dataframe se debería de ignorar.

* Carga el archivo a un dataframe usando el código necesario para omitir la última fila.
* Usa df.tail(3) para demostrar que no has cargado la última línea
* Imprime la cantidad de filas y columnas del dataframe

In [2]:
import pandas as pd

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
df = pd.read_csv('/content/drive/MyDrive/ClassFiles/Unidad02/miaad-nyc-r-s.csv', skipfooter=1, engine='python')
df.head(5)

,Unnamed: 0,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,EASE-MENT,BUILDING CLASS AT PRESENT,ADDRESS,...,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE PRICE,SALE DATE
0,4,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,392,6,,C2,153 AVENUE B,...,5,0,5,1633,6440,1900,2,C2,6625000,2017-07-19 00:00:00
1,5,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,399,26,,C7,234 EAST 4TH STREET,...,28,3,31,4616,18690,1900,2,C7,-,2016-12-14 00:00:00
2,6,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,399,39,,C7,197 EAST 3RD STREET,...,16,1,17,2212,7803,1900,2,C7,-,2016-12-09 00:00:00
3,7,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,402,21,,C4,154 EAST 7TH STREET,...,10,0,10,2272,6794,1913,2,C4,3936272,2016-09-23 00:00:00
4,8,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,404,55,,C2,301 EAST 10TH STREET,...,6,0,6,2369,4615,1900,2,C2,8000000,2016-11-17 00:00:00

In [5]:
df.tail(3)

,Unnamed: 0,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,EASE-MENT,BUILDING CLASS AT PRESENT,ADDRESS,...,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE PRICE,SALE DATE
84545,8411,5,WOODROW,02 TWO FAMILY DWELLINGS,1,7351,60,,B2,49 PITNEY AVENUE,...,2,0,2,4000,1496,1925,1,B2,460000,2017-07-05 00:00:00
84546,8412,5,WOODROW,22 STORE BUILDINGS,4,7100,28,,K6,2730 ARTHUR KILL ROAD,...,0,7,7,208033,64117,2001,4,K6,11693337,2016-12-21 00:00:00
84547,8413,5,WOODROW,35 INDOOR PUBLIC AND CULTURAL FACILITIES,4,7105,679,,P9,155 CLAY PIT ROAD,...,0,1,1,10796,2400,2006,4,P9,69300,2016-10-27 00:00:00

In [6]:
df.shape

(84548, 22)

# Práctica 13: Cambiar nombre de columna

* Imprime los nombres de la columnas del archivo
* Asegúrate que el nombre de la primera columna debería ser INDEX MIAAD. Si esto no es así, entonces cambia el nombre de la columna y vuelve a imprimir los nombres para mostrar el cambio realizado. Después del cambio debería aparecer INDEX MIAAD.

In [7]:
df.columns

Index(['Unnamed: 0', 'BOROUGH', 'NEIGHBORHOOD', 'BUILDING CLASS CATEGORY',
       'TAX CLASS AT PRESENT', 'BLOCK', 'LOT', 'EASE-MENT',
       'BUILDING CLASS AT PRESENT', 'ADDRESS', 'APARTMENT NUMBER', 'ZIP CODE',
       'RESIDENTIAL UNITS', 'COMMERCIAL UNITS', 'TOTAL UNITS',
       'LAND SQUARE FEET', 'GROSS SQUARE FEET', 'YEAR BUILT',
       'TAX CLASS AT TIME OF SALE', 'BUILDING CLASS AT TIME OF SALE',
       'SALE PRICE', 'SALE DATE'],
      dtype='object')

In [8]:
df.rename(columns={df.columns[0]: "INDEX MIAAD"}, inplace=True)

In [9]:
df.columns

Index(['INDEX MIAAD', 'BOROUGH', 'NEIGHBORHOOD', 'BUILDING CLASS CATEGORY',
       'TAX CLASS AT PRESENT', 'BLOCK', 'LOT', 'EASE-MENT',
       'BUILDING CLASS AT PRESENT', 'ADDRESS', 'APARTMENT NUMBER', 'ZIP CODE',
       'RESIDENTIAL UNITS', 'COMMERCIAL UNITS', 'TOTAL UNITS',
       'LAND SQUARE FEET', 'GROSS SQUARE FEET', 'YEAR BUILT',
       'TAX CLASS AT TIME OF SALE', 'BUILDING CLASS AT TIME OF SALE',
       'SALE PRICE', 'SALE DATE'],
      dtype='object')

# Práctica 14: Normalización de los nombres de la columna.

* Normaliza los nombres de las columnas, los cuales deberán estar en minúsculas. Asimismo, reemplaza los espacios con guion bajo
* Imprime los nombres de las columnas para demostrar que has realizado la normalización.

In [10]:
df.columns = (
    df.columns
        .str.lower()
        .str.strip()
        .str.replace(r"\s+", "_", regex=True)
)

In [11]:
df.columns

Index(['index_miaad', 'borough', 'neighborhood', 'building_class_category',
       'tax_class_at_present', 'block', 'lot', 'ease-ment',
       'building_class_at_present', 'address', 'apartment_number', 'zip_code',
       'residential_units', 'commercial_units', 'total_units',
       'land_square_feet', 'gross_square_feet', 'year_built',
       'tax_class_at_time_of_sale', 'building_class_at_time_of_sale',
       'sale_price', 'sale_date'],
      dtype='object')

# Práctica 15: Errores en los Tipos de Datos

* Imprime los tipos de datos de cada columna.
* Asegúrate que las columnas de *SALE PRICE(sale_price), LAND SQUARE FEET (land_square_feet), GROSS SQUARE FEET (gross_square_feet)* sean de tipo flotante. Escribe qué tipo de dato tienen asignado. Si no son correctos, realiza el cambio.
* Imprime de nuevo los tipos de datos para demostrar que has arreglado el problema.

In [12]:
df.dtypes

index_miaad                        int64
borough                            int64
neighborhood                      object
building_class_category           object
tax_class_at_present              object
block                              int64
lot                                int64
ease-ment                         object
building_class_at_present         object
address                           object
apartment_number                  object
zip_code                           int64
residential_units                  int64
commercial_units                   int64
total_units                        int64
land_square_feet                  object
gross_square_feet                 object
year_built                         int64
tax_class_at_time_of_sale          int64
building_class_at_time_of_sale    object
sale_price                        object
sale_date                         object
dtype: object

In [13]:
print("sale_price:", df["sale_price"].dtype)
print("land_square_feet:", df["land_square_feet"].dtype)
print("gross_square_feet:", df["gross_square_feet"].dtype)

sale_price: object
land_square_feet: object
gross_square_feet: object

In [14]:
# df['sale_price'] = df['sale_price'].astype(float)
# df['land_square_feet'] = df['land_square_feet'].astype(float)
# df['gross_square_feet'] = df['gross_square_feet'].astype(float)

df['sale_price'] = pd.to_numeric(df['sale_price'], errors='coerce')
df['land_square_feet'] = pd.to_numeric(df['land_square_feet'], errors='coerce')
df['gross_square_feet'] = pd.to_numeric(df['gross_square_feet'], errors='coerce')

In [16]:
print("sale_price:", df["sale_price"].dtype)
print("land_square_feet:", df["land_square_feet"].dtype)
print("gross_square_feet:", df["gross_square_feet"].dtype)

sale_price: float64
land_square_feet: float64
gross_square_feet: float64

# Práctica 16: Genera el diccionario de datos del dataframe preprocesado. Imprime el contenido de dicho diccionario

In [19]:
diccionario_datos = pd.DataFrame({"Nombre de columna": df.columns,
                                  "Tipo de dato": [str(df[col].dtype) for col in df.columns]})

#Imprimimos el diccionario
print(diccionario_datos)

                 Nombre de columna Tipo de dato
0                      index_miaad        int64
1                          borough        int64
2                     neighborhood       object
3          building_class_category       object
4             tax_class_at_present       object
5                            block        int64
6                              lot        int64
7                        ease-ment       object
8        building_class_at_present       object
9                          address       object
10                apartment_number       object
11                        zip_code        int64
12               residential_units        int64
13                commercial_units        int64
14                     total_units        int64
15                land_square_feet      float64
16               gross_square_feet      float64
17                      year_built        int64
18       tax_class_at_time_of_sale        int64
19  building_class_at_time_of_sale       object
20                      sale_price      float64
21                       sale_date       object