<a href="https://colab.research.google.com/github/marioarsw/AnaliticaDescriptiva/blob/main/practicas/practica18_267370.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Maestría en Inteligencia Artificial y Analítica de Datos


*   Curso: Programación para Analítica Descriptiva y Predictiva
*   Semestre: Enero-Junio
*   Profesor: Dr. Vicente García Jiménez

## Mario Amador - 267370.

El objetivo de esta actividad es que los estudiantes practiquen los temas vistos de limpieza y transformación de datos categóricos.

Instrucciones:

1. Descarga el archivo airdata.csv, proporcionado en esta tarea. También lo puedes encontrar en recursos.
2. Crea un notebook en colab y guarda el archivo csv  en tu drive.
3. Agrega secciones en el colab poniendo como título el nombre de cada ejercicio.

In [3]:
import pandas as pd

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Ejercicio 01: Tipo de Datos Correcto

1. Carga el conjunto de datos airdata.csv y verifica que cada columna tenga el tipo de datos correcto
2. Si una columna de tipo temporal no está en el tipo de correcto realiza la conversión.
3. Usa dtypes para mostrar que cada columna, principalmente la que contiene datos temporales, está en el tipo de datos correcto
Imprime las primeras tres líneas.

In [9]:
airdata = pd.read_csv('/content/drive/MyDrive/ClassFiles/Unidad02/Airdata.csv')
airdata.head(5)

,DateTime,Temperature,Humidity,Wind_Speed,Wind_Direction,NO2_Location_A,NO2_Location_B,NO2_Location_C
0,1/1/2020 0:00,2.180529,87,1.484318,75.963760,39.23,52.88,62.37
1,1/1/2020 1:00,1.490529,89,2.741678,113.198590,38.30,44.95,52.53
2,1/1/2020 2:00,1.690529,85,3.563818,135.000000,NaN,48.40,54.80
3,1/1/2020 3:00,1.430529,84,2.811690,129.805570,37.28,47.18,50.80
4,1/1/2020 4:00,0.840529,86,1.800000,126.869896,29.97,41.48,54.43

In [10]:
airdata.dtypes

DateTime           object
Temperature       float64
Humidity            int64
Wind_Speed        float64
Wind_Direction    float64
NO2_Location_A    float64
NO2_Location_B    float64
NO2_Location_C    float64
dtype: object

In [11]:
airdata['DateTime']=pd.to_datetime(airdata['DateTime'])

In [12]:
airdata.dtypes

DateTime          datetime64[ns]
Temperature              float64
Humidity                   int64
Wind_Speed               float64
Wind_Direction           float64
NO2_Location_A           float64
NO2_Location_B           float64
NO2_Location_C           float64
dtype: object

In [14]:
airdata.head(3)

,DateTime,Temperature,Humidity,Wind_Speed,Wind_Direction,NO2_Location_A,NO2_Location_B,NO2_Location_C
0,2020-01-01 00:00:00,2.180529,87,1.484318,75.96376,39.23,52.88,62.37
1,2020-01-01 01:00:00,1.490529,89,2.741678,113.19859,38.30,44.95,52.53
2,2020-01-01 02:00:00,1.690529,85,3.563818,135.00000,NaN,48.40,54.80

# Ejercicio 02: Extraer componentes de fecha y tiempo

1. De la columna 'DateTime' extrae el año, mes, día y hora. Crea una nueva columna para cada componente que extraes.
2. Imprime las primeras tres líneas del dataframe que ahora deberá tener 4 nuevas columnas.

In [15]:
airdata['year'] = airdata['DateTime'].dt.year
airdata['month'] = airdata['DateTime'].dt.month
airdata['day'] = airdata['DateTime'].dt.day
airdata['hour'] = airdata['DateTime'].dt.hour

In [16]:
airdata.head(3)

,DateTime,Temperature,Humidity,Wind_Speed,Wind_Direction,NO2_Location_A,NO2_Location_B,NO2_Location_C,year,month,day,hour
0,2020-01-01 00:00:00,2.180529,87,1.484318,75.96376,39.23,52.88,62.37,2020,1,1,0
1,2020-01-01 01:00:00,1.490529,89,2.741678,113.19859,38.30,44.95,52.53,2020,1,1,1
2,2020-01-01 02:00:00,1.690529,85,3.563818,135.00000,NaN,48.40,54.80,2020,1,1,2

# Ejercicio 03: Aritmética - Suma de Intervalos (timedelta)

1. Suma 10 días, 7 horas y 15 minutos a cada elemento de la columna 'DateTime'. 2. Guarda el resultado en una nueva columna y agrega al dataframe.
3. Imprime la columna 'DateTime' y la columna que resulta de sumar 10 días, 7 horas y 15 minutos.

In [17]:
airdata['more_time'] = airdata['DateTime'] + pd.Timedelta(days=10, hours=7, minutes=15)

In [18]:
airdata[['DateTime', 'more_time']]

                DateTime           more_time
0    2020-01-01 00:00:00 2020-01-11 07:15:00
1    2020-01-01 01:00:00 2020-01-11 08:15:00
2    2020-01-01 02:00:00 2020-01-11 09:15:00
3    2020-01-01 03:00:00 2020-01-11 10:15:00
4    2020-01-01 04:00:00 2020-01-11 11:15:00
...                  ...                 ...
8779 2020-12-31 19:00:00 2021-01-11 02:15:00
8780 2020-12-31 20:00:00 2021-01-11 03:15:00
8781 2020-12-31 21:00:00 2021-01-11 04:15:00
8782 2020-12-31 22:00:00 2021-01-11 05:15:00
8783 2020-12-31 23:00:00 2021-01-11 06:15:00

[8784 rows x 2 columns]

# Ejercicio 04: Timestamp

1. Convierte la columna 'DateTime' la cual tiene un formato de fecha legible a a timestamp Unix. Guarda el resultado en una nueva columna.
2. Imprime las primeras tres filas de  la columna 'DateTime' y la columna que representa dicha fecha en timestamp Unix.

In [19]:
airdata['timestamp_unix'] = pd.to_datetime(airdata['DateTime']).astype('int64') // 10**9

# astype('int64')
# convertir la fecha a número de nanosegundos desde 1970.

# // 10**9
# dividir entre 1,000,000,000 para convertir nanosegundos → segundo

In [20]:
print(airdata[['DateTime', 'timestamp_unix']].head(3))

             DateTime  timestamp_unix
0 2020-01-01 00:00:00      1577836800
1 2020-01-01 01:00:00      1577840400
2 2020-01-01 02:00:00      1577844000

# Ejercicio 05: Filtrado de Fechas

1. Utiliza la columna 'DateTime' y Filtra aquellas fechas que son mayores a 2020-11-01.
2. Imprime el resultado.

In [21]:
print(airdata['DateTime'] > '2020-11-01')

0       False
1       False
2       False
3       False
4       False
        ...
8779     True
8780     True
8781     True
8782     True
8783     True
Name: DateTime, Length: 8784, dtype: bool